export const userConstants = {
  SET_USER: 'SET_USER',
  SET_USER_ID: 'SET_USER_ID',
  SET_ROLE_USER: 'SET_ROLE_USER',
  SET_LOGGED_IN: 'SET_LOGGED_IN',
  SET_TOKEN_LOGGED_IN: 'SET_TOKEN_LOGGED_IN'
}
